name: vet
description: "runs go vet"
inputs:
  go-version:
    description: "go version"
    required: true
    type: string
runs:
  using: "composite"
  steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-go@v2
       with:
         go-version: ${{ inputs.go-version }}
     - name: vet
       run: |
         go vet ./...
       shell: bash
