name: Build

on:
   workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      target:
        required: true
        type: string
      dockerfile:
        required: false
        default: ./build/Dockerfile
        type: string
      repo:
        required: false
        default: clambin
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/actions/go/test@actions
        with:
          go-version: ${{ inputs.go-version }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/actions/go/lint@actions
        with:
          go-version: ${{ inputs.go-version }}
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/actions/go/vet@actions
        with:
          go-version: ${{ inputs.go-version }}
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/actions/go/vulnerabilities@actions
        with:
          go-version: ${{ inputs.go-version }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm, arm64 ]
    steps:
      - uses: clambin/workflows/actions/go/build@actions
        with:
          go-version: ${{ inputs.go-version }}
          target: ${{ inputs.target }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - vet
      - vulnerabilities
      - build
    steps:
      - uses: clambin/workflows/actions/docker@actions
        with:
          target: ${{ inputs.target }}
          repo: ${{ inputs.repo }}
          dockerfile: ${{ inputs.dockerfile }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

