name: Vulnerabilities

on:
   workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/actions/go/vulnerabilities@actions
        with:
          go-version: ${{ inputs.go-version }}

