name: Build

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64 # ,linux/arm64
      dockerfile:
        required: false
        type: string
        default: build/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5.8.0
        id: docker_meta
        with:
          images: ${{ inputs.image }}
          flavor: |
            latest=false
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
