name: Build

on:
   workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.19"
      target:
        required: true
        type: string
      docker:
        description: "build a docker container for the target"
        required: false
        default: true
        type: boolean
      dockerfile:
        required: false
        default: "./build/Dockerfile"
        type: string
      repo:
        required: false
        default: "clambin"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - name: Version number
        run: |
          echo "build_version=${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash
      - name: build
        env:
          TARGET: ${{ inputs.target }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ env.build_version }}
        run: |
          CGO_ENABLED=0 go build \
              -ldflags "-X github.com/$GITHUB_REPOSITORY/version.BuildVersion=$VERSION" \
              -o bld/$TARGET-$GOOS-$GOARCH \
              cmd/$TARGET/$TARGET.go
        shell: bash
      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bld/*
  docker:
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.target }}-linux-arm
          path: ./bld
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.target }}-linux-arm64
          path: ./bld
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.target }}-linux-amd64
          path: ./bld
      - name: Fix permissions
        run: chmod +x bld/*
        shell: bash
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4.2.0
        id: docker_meta
        with:
          images: ghcr.io/${{ inputs.repo }}/${{ inputs.target }}
          tags: |
            type=sha
            type=sha,suffix=-{{date 'YYYYMMDDHHmmssSS'}}
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{ steps.docker_meta.outputs.version }}
