name: Release

on:
   workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: crowbarmaster/GH-Automatic-Releases@v1.6.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
