name: Release

on:
   workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.17"
      target:
        required: true
        type: string
      dockerfile:
        required: false
        default: ./build/Dockerfile
        type: string
      repo:
        required: false
        default: clambin
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts
      - name: Move binaries into place
        run: |
          mkdir bld
          mv artifacts/*/* bld
        shell: bash
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            bld/*
