name: Release

on:
   workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Move binaries into place
        run: |
          mkdir bld
          mv artifacts/*/* bld
        shell: bash
      - uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
      - uses: svenstaro/upload-release-action@v2
        with:
          file: bld/*
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}