name: Test

on:
   workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/test.yaml@actions
        with:
          go-version: ${{ inputs.go-version }}
