name: Test

on:
  workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.17"
      all-tests:
        description: "set false to only run go test"
        type: boolean
        required: false
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/test@main
        with:
          go-version: ${{ inputs.go-version }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
      - uses: clambin/workflows/.github/actions/go/vulnerabilities@main
        with:
          go-version: ${{ inputs.go-version }}
  lint:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/lint@main
        with:
          go-version: ${{ inputs.go-version }}
  vet:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/vet@main
        with:
          go-version: ${{ inputs.go-version }}
  codeql:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: github/codeql-action/init@v1
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
  vulnerabilities:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/vulnerabilities@main
        with:
          go-version: ${{ inputs.go-version }}
