name: Test

on:
   workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/test@main
        with:
          go-version: ${{ inputs.go-version }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
      - uses: clambin/workflows/.github/actions/go/vulnerabilities@main
        with:
          go-version: ${{ inputs.go-version }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/lint@main
        with:
          go-version: ${{ inputs.go-version }}
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/vet@main
        with:
          go-version: ${{ inputs.go-version }}
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/vulnerabilities@main
        with:
          go-version: ${{ inputs.go-version }}
