name: Test

on:
  workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.17"
      all-tests:
        description: "set false to only run go test"
        type: boolean
        required: false
        default: true

jobs:
  go-lint:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
        shell: bash
  go-vet:
    if: ${{ inputs.all-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
        shell: bash
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        shell: bash
      - name: upload code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
