name: Vulnerabilities

on:
   workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.17"

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: clambin/workflows/.github/actions/go/vulnerabilities@main
        with:
          go-version: ${{ inputs.go-version }}

