name: Vulnerabilities

on:
   workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: WriteGoList
        run: go list -json -deps all > go.list
      - uses: sonatype-nexus-community/nancy-github-action@main

