name: Vulnerabilities

on:
   workflow_call:
    inputs:
      go-version:
        description: "go version to use for test & build"
        type: string
        required: false
        default: "1.19"

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - name: WriteGoList
        run: go list -json -deps all > go.list
        shell: bash
      - uses: sonatype-nexus-community/nancy-github-action@main
