name: Vulnerabilities

on:
   workflow_call:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1.0.4
        with:
          go-version-input: 1.24
